### PR TITLE
Update documentation for leaving a room.

### PR DESCRIPTION
**Pull request by vramana**

### CODE REVIEW

**Comment by MadLittleMods** [comment]
@vramana Sorry for not addressing this, I haven't had a chance to test whether `room.leave` actually doesn't work.

**Comment by vramana** [comment]
@MadLittleMods It was present in older version. Now it's not even present. I only knew this because I looked at your tests. May you want to add `room.leave` in future but at least till then this may help some people.

**Comment by MadLittleMods** [comment]
`room.leave` was removed in https://github.com/gitterHQ/node-gitter/commit/21aef59cca2b4c3123fc7438fa5bee6b85bc66ed#diff-0d5d8ebdb618a19c0e89e348b0ccff1eL75

Just as a sanity check, I see this is similar to the test written, https://github.com/gitterHQ/node-gitter/blob/915c51c350183d635eabc6fc20f6e7252f163d08/test/rooms-test.js#L58

**Comment by MadLittleMods** [comment]
Thanks for the contribution @vramana :tada:

**Pull request merged**
